server:
  port: 8080
  context-path: /demo
swagger:
  # 是否启用swagger，默认：true
  enabled: true
  # 标题
  title: swagger-demo API 管理
  # 描述
  description: 这里是 swagger-demo API 管理的描述信息
  # 版本
  version: 0.0.1-SNAPSHOT
  # 许可证
  license: MIT License
  # 许可证URL
  licenseUrl: https://github.com/xkcoding/spring-boot-demo/blob/master/LICENSE
  # 许可证URL
  termsOfServiceUrl: https://github.com/xkcoding/spring-boot-demo/blob/master/LICENSE
  contact:
      # 维护人
      name: xkcoding
      # 维护人URL
      url: http://xkcoding.com
      # 维护人URL
      email: 237497819@qq.com
  # swagger扫描的基础包，默认：全扫描
  base-package: com.xkcoding
  # 需要处理的基础URL规则，默认：/**
  base-path: /**
  # 需要排除的URL规则，默认：空
  exclude-path: /error
# swagger.host=文档的host信息，默认：空
# swagger.globalOperationParameters[0].name=参数名
# swagger.globalOperationParameters[0].description=描述信息
# swagger.globalOperationParameters[0].modelRef=指定参数类型
# swagger.globalOperationParameters[0].parameterType=指定参数存放位置,可选header,query,path,body.form
# swagger.globalOperationParameters[0].required=指定参数是否必传，true,false