server:
  port: 8080
  context-path: /demo
application:
  name: spring-boot-demo-properties
  version: 0.0.1-SNAPSHOT
  author:
    name: xkcoding
    website: xkcoding.com
    qq: 237497819
    phone-number: 18601224166